# Generated by Django 4.0.5 on 2022-06-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('classification_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
                'db_table': 'classifications',
                'managed': False,
            },
        ),
    ]
