# Generated by Django 4.0.5 on 2022-06-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classification',
            table=None,
        ),
    ]
